# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('muss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forum',
            name='topics_count',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='Total topics'),
        ),
    ]
