# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muss', '0003_auto_20170831_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-is_top', 'forum', '-date', 'title', '-last_activity'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description',
            field=models.TextField(blank=True, help_text='Description site.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords for the SEO.', verbose_name='Keywords'),
        ),
    ]
