# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muss', '0005_hitcounttopicmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HitcountTopicModel',
            new_name='HitcountTopic',
        ),
    ]
