# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muss', '0009_auto_20171001_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likecomment',
            old_name='data',
            new_name='data_comment',
        ),
    ]
