# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muss', '0010_auto_20171001_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likecomment',
            old_name='data_comment',
            new_name='users',
        ),
    ]
