# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 11:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('muss', '0011_auto_20171001_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liketopic',
            name='user',
        ),
        migrations.AddField(
            model_name='liketopic',
            name='users',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
            preserve_default=False,
        ),
    ]
