# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muss', '0014_auto_20171007_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecomment',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes_comment', to='muss.Comment'),
        ),
    ]
