# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muss', '0016_auto_20171007_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_topic',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
