# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import muss.models
import muss.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muss', '0017_auto_20171016_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=muss.models.Upload.generate_path, validators=[muss.validators.valid_extension_image], verbose_name='File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_uploads', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
