# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muss', '0018_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
