# Generated by Django 2.0 on 2017-12-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muss', '0019_auto_20171116_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='If the user is enabled in the forum', verbose_name='Enable register'),
        ),
    ]
